services:
  zms-base:
    build: ./zms-base
    image: zms-base:latest
    entrypoint: "bash -c"
    command: "exit 0"

  zope:
    image: zms-base:latest
    stop_grace_period: 1s # SIGKILL after 1s, as zope is always taking the full 10 seconds
    ports:
      - 80:80
    volumes:
      - ./zope/etc/:/home/zope/etc/
      - ./zope/var/:/home/zope/var/

  zeo:
    image: zms-base:latest
    command: runzeo --configure etc/zeo.conf
    volumes:
      - ./zeo/etc/:/home/zope/etc/
      - ./zeo/var/:/home/zope/var/
