services:
  zms-base:
    build: ./zms-base
    image: zms-base:latest
    entrypoint: "bash -c"
    command: "exit 0"

  zope:
    image: zms-base:latest
    ports:
      - 80:80
    volumes:
      - ./zope/etc/:/home/zope/instance/etc/
      - ./zope/var/:/home/zope/instance/var/

  zeo:
    image: zms-base:latest
    command: runzeo --configure instance/etc/zeo.conf
    volumes:
      - ./zeo/etc/:/home/zope/instance/etc/
      - ./zeo/var/:/home/zope/instance/var/
